AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'x-experimental'"
        AllowOrigin: "'*'"

  StarsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: stars/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        Stars:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stars
            Method: get
            RestApiId:
              Ref: ApiGatewayApi


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  StarsApi:
    Description: "API Gateway endpoint URL for Prod stage for Stars function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stars/"
  StarsFunction:
    Description: "Stars Lambda Function ARN"
    Value: !GetAtt StarsFunction.Arn
  StarsFunctionIamRole:
    Description: "Implicit IAM Role created for Stars function"
    Value: !GetAtt StarsFunctionRole.Arn
