AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python-cognito-sam

  Sample SAM Template for python-cognito-sam

Globals:
  Function:
    Timeout: 30

Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: python-cognito-sam


  HomeFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: cognito_function/
      Policies:
        - AmazonSSMReadOnlyAccess
      Handler: app.home_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Home:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: ApiGatewayApi


  TokenFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: cognito_function/
      Policies:
        - AmazonSSMReadOnlyAccess
      Handler: app.token_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Home:
          Type: Api
          Properties:
            Path: /token
            Method: get
            RestApiId:
              Ref: ApiGatewayApi



Outputs:
  HomePages:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/python-cognito-sam/"
